### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by Rui914** [Rui914/playeranim#4]
- [x] ~~Add LAY animation #2~~
- [x] ~~Fix sneak animation~~
- [x] ~~Support default animation api~~
- [x] ~~Add SIT animation~~
